### ISSUE TITLE
Unable to reproduce results

### ISSUE THREAD

**Issue by abhid1** [pranav-ust/BERT-keyphrase-extraction#5]
Hi, 

I've tried replicating your results for task 1 and task 2, but keep getting drastically lower F1 scores. I am getting an F1 score of 44 for task 1, and an average of 36.79 for task 2. Any suggestions?

Also this is really nice work, thanks for posting this.

**Comment by pranav-ust** [comment]
Hmm, I haven't updated and checked over this code for a long time, so something must have been changed. I will be updating (and much over-improving this code) quite soon.

**Comment by pranav-ust** [comment]
Recently, I have been using the similar model again, and surprisingly the pretrained model does not work well this time. So I strongly think that it's a fault from AllenAI's side. If you check their issues and pull requests, you will notice that they gave up on Semeval dataset and did not include this in their paper. 

I would appreciate if you do a grid search and let me know the results.

**Comment by abhid1** [comment]
I'm not sure how, but when I downgraded my pytorch_pretrained_bert version from 0.6.2 to 0.4.0, I was getting higher BLEU scores (similar to what you reported).

**Comment by pranav-ust** [comment]
I have heard that huggingface made a few mistakes in their architecture back then. I am using huggingface transformers now, and I am not able to reproduce the results.

**Comment by HarshRangwala** [comment]
Hi. @abhid1 Can you please share how did you execute this project?
I am getting this error when I run the train command:
```
device: cpu, n_gpu: 0, 16-bits training: False
Loading the datasets...
Model name 'model/' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'model/' was a path or url but couldn't find any file associated to this path or url.
Traceback (most recent call last):
  File "train.py", line 168, in <module>
    train_data = data_loader.load_data('train')
  File "D:\MyWorkNN\PyTorch BERT\BERT-keyphrase-extraction-master\BERT-keyphrase-extraction-master\data_loader.py", line 83, in load_data
    self.load_sentences_tags(sentences_file, tags_path, data)
  File "D:\MyWorkNN\PyTorch BERT\BERT-keyphrase-extraction-master\BERT-keyphrase-extraction-master\data_loader.py", line 48, in load_sentences_tags
    for line in file:
  File "C:\Users\Anuj\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2667: character maps to <undefined>
```

**Comment by salman-ahmed-khan** [comment]
Hi Pranav, I am facing problems in steps to train this on google colab. For some reason I am getting an error saying 

:


device: cpu, n_gpu: 0, 16-bits training: False
Loading the datasets...
loading vocabulary file ./model/vocab.txt
Traceback (most recent call last):
  File "train.py", line 168, in <module>
    train_data = data_loader.load_data('train')
  File "/content/BERT-keyphrase-extraction/data_loader.py", line 83, in load_data
    self.load_sentences_tags(sentences_file, tags_path, data)
  File "/content/BERT-keyphrase-extraction/data_loader.py", line 51, in load_sentences_tags
    sentences.append(self.tokenizer.convert_tokens_to_ids(tokens))
  File "/usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/tokenization.py", line 121, in convert_tokens_to_ids
    ids.append(self.vocab[token])
KeyError: 'nonzero'

**Comment by yashrooprai** [comment]
> Hi Pranav, I am facing problems in steps to train this on google colab. For some reason I am getting an error saying
> 
> :
> 
> device: cpu, n_gpu: 0, 16-bits training: False Loading the datasets... loading vocabulary file ./model/vocab.txt Traceback (most recent call last): File "train.py", line 168, in train_data = data_loader.load_data('train') File "/content/BERT-keyphrase-extraction/data_loader.py", line 83, in load_data self.load_sentences_tags(sentences_file, tags_path, data) File "/content/BERT-keyphrase-extraction/data_loader.py", line 51, in load_sentences_tags sentences.append(self.tokenizer.convert_tokens_to_ids(tokens)) File "/usr/local/lib/python3.6/dist-packages/pytorch_pretrained_bert/tokenization.py", line 121, in convert_tokens_to_ids ids.append(self.vocab[token]) KeyError: 'nonzero'

Were you able to fix this error?
